import { CatalogTemplate, CatalogConfig } from './types';
import { suggestIconForTopic } from './topicIcons';

export const TEMPLATES: CatalogTemplate[] = [
  // 1. Loja de Semi Joias (Exatamente no estilo minimalista refinado da foto)
  {
    id: 'semijoias',
    name: 'Loja de Semi Joias & Folheados',
    categoryName: 'Semi Joias & Folheados',
    tagline: 'Design minimalista de luxo para semijoias finas banhadas a ouro 18k e prata 925',
    description: 'Estética clean e minimalista idêntica às boutiques de joias mais elegantes: topo com logotipo centralizado, chamada poética e produtos com fotos em expositores.',
    thumbnail: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80',
    config: {
      storeName: 'Joias & Semijoias',
      slug: 'semijoias',
      bio: 'Semijoias com 10 camadas de banho nobre e acabamento premium.',
      heroTagline: 'SEMIJOIAS FINAS',
      heroTitle: 'As semijoias certas para você',
      heroHighlightWord: 'brilhar',
      heroSubtitle: 'Encontre o acessório perfeito para o seu estilo.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=1200&auto=format&fit=crop&q=80',
      instagram: '',
      whatsapp: '',
      locationText: '',
      templateId: 'semijoias',
      theme: {
        primaryColor: '#B8860B', // Dourado quente nobre
        accentColor: '#D4AF37',
        backgroundColor: '#FFFFFF', // Fundo branco minimalista
        cardBackground: '#FFFFFF',
        textColor: '#1C1917',
        mutedTextColor: '#78716C',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'semijoias-cormorant',
        typographyPresetId: 'semijoias-cormorant',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: false,
      },
      progressiveDiscounts: [
        { minItems: 2, discountPercent: 10, label: 'Leve 2 peças e ganhe 10% OFF' },
        { minItems: 3, discountPercent: 15, label: 'Leve 3 peças e ganhe 15% OFF' },
      ],
      shipping: {
        pickupEnabled: true,
        pickupLabel: 'Retirada no Showroom (Moema/SP)',
        pickupAddress: 'Av. Ibirapuera, 2120',
        motoboyEnabled: true,
        motoboyPrice: 15.0,
        motoboyEstimate: 'Entrega hoje até as 19h',
        sedexEnabled: true,
        sedexPrice: 22.0,
        sedexEstimate: 'Correios todo o Brasil',
        freeShippingAbove: 299.0,
      },
      wholesaleConfig: {
        enabled: true,
        minPieces: 6,
        defaultDiscountPercent: 35,
        requireMinPieces: true,
      },
      topics: [
        'RELÓGIOS',
        'PULSEIRAS',
        'SMARTWATCHES',
        'TELEFONES',
        'FONES DE OUVIDO',
        'BRINCOS',
        'COLAR / CHOKER',
        'BRACELETES',
        'ANEL',
      ],
      topicIcons: {
        'RELÓGIOS': 'watch',
        'PULSEIRAS': 'bracelet',
        'SMARTWATCHES': 'smartwatch',
        'TELEFONES': 'smartphone',
        'FONES DE OUVIDO': 'headphones',
        'BRINCOS': 'gem',
        'COLAR / CHOKER': 'gem',
        'BRACELETES': 'bangle',
        'ANEL': 'gem',
      },
      products: [],
    },
  },

  // 2. Boutique de Roupas (Chic & Minimalist)
  {
    id: 'boutique',
    name: 'Boutique de Roupas',
    categoryName: 'Moda Feminina & Alfaiataria',
    tagline: 'Minimalismo chique, alfaiataria em linho e cortes atemporais',
    description: 'Design editorial limpo com bastante respiro, tipografia refinada e foco total nas peças.',
    thumbnail: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&auto=format&fit=crop&q=80',
    config: {
      storeName: 'AURA BOUTIQUE',
      slug: 'aura-boutique',
      bio: 'Curadoria em alfaiataria fina, linho puro italiano e peças atemporais.',
      heroTagline: 'ALFAIATARIA & LINHO PURO',
      heroTitle: 'A elegância certa para o seu',
      heroHighlightWord: 'estilo',
      heroSubtitle: 'Peças selecionadas à mão para compor um guarda-roupa atemporal e sofisticado.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&auto=format&fit=crop&q=80',
      instagram: '@aura.boutiqueoficial',
      whatsapp: '5511988887777',
      locationText: 'Jardins, São Paulo • Envio Express',
      templateId: 'boutique',
      theme: {
        primaryColor: '#292524',
        accentColor: '#785936',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#1C1917',
        mutedTextColor: '#78716C',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'boutique-playfair',
        typographyPresetId: 'boutique-playfair',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: false,
      },
      progressiveDiscounts: [
        { minItems: 2, discountPercent: 10, label: 'Compre 2 peças ganhe 10% OFF' },
        { minItems: 3, discountPercent: 15, label: 'Compre 3 peças ganhe 15% OFF' },
      ],
      shipping: {
        pickupEnabled: true,
        pickupLabel: 'Retirada no Showroom (Jardins/SP)',
        pickupAddress: 'Rua Oscar Freire, 1140',
        motoboyEnabled: true,
        motoboyPrice: 15.0,
        motoboyEstimate: 'Entrega hoje até 19h',
        sedexEnabled: true,
        sedexPrice: 28.5,
        sedexEstimate: '1 a 3 dias úteis',
        freeShippingAbove: 399.0,
      },
      wholesaleConfig: {
        enabled: true,
        minPieces: 6,
        defaultDiscountPercent: 30,
        requireMinPieces: true,
      },
      pinBadgedProductsToTop: true,
      outOfStockBehavior: 'badge-sold-out',
      topics: ['BLAZERS', 'VESTIDOS', 'CALÇAS', 'CAMISAS', 'ROUPA MASCULINA'],
      products: [],
    },
  },

  // 3. Roupas de Academia / Fitness (Clean Activewear)
  {
    id: 'fitness',
    name: 'Roupas de Academia & Fitness',
    categoryName: 'Activewear & Moda Fitness',
    tagline: 'Linhas minimalistas, sustentação e zero transparência',
    description: 'Visual moderno e minimalista com foco nas modelagens escultoras e tecnologia dos tecidos.',
    thumbnail: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&auto=format&fit=crop&q=80',
    config: {
      storeName: 'PULSE ACTIVEWEAR',
      slug: 'pulse-fitness',
      bio: 'Roupas de treino com alta sustentação e zero transparência testada em agachamento.',
      heroTagline: 'ALTA PERFORMANCE & CONFORTO',
      heroTitle: 'O suporte ideal para você se',
      heroHighlightWord: 'superar',
      heroSubtitle: 'Modelagens anatômicas, tecidos sem costura e secagem ultra-rápida.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1538805060514-97d9cc17730c?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=1200&auto=format&fit=crop&q=80',
      instagram: '@pulse.active',
      whatsapp: '5511966665555',
      locationText: 'Brasil • Entregas Rápidas',
      templateId: 'fitness',
      theme: {
        primaryColor: '#0F172A',
        accentColor: '#10B981',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#0F172A',
        mutedTextColor: '#64748B',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'fitness-oswald',
        typographyPresetId: 'fitness-oswald',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: false,
        heroCardBackground: '#0F172A',
        heroCardTextColor: '#FFFFFF',
        heroCardBorderColor: '#1E293B',
      },
      progressiveDiscounts: [
        { minItems: 2, discountPercent: 10, label: 'Monte o Look: 2 peças com 10% OFF' },
        { minItems: 3, discountPercent: 18, label: 'Kit Treino: 3 peças com 18% OFF' },
      ],
      shipping: {
        pickupEnabled: true,
        pickupLabel: 'Retirada na Academia Parceira',
        pickupAddress: 'Rua dos Pinheiros, 800',
        motoboyEnabled: true,
        motoboyPrice: 14.0,
        motoboyEstimate: 'Entrega hoje',
        sedexEnabled: true,
        sedexPrice: 24.0,
        sedexEstimate: '2 a 4 dias úteis',
        freeShippingAbove: 249.0,
      },
      wholesaleConfig: {
        enabled: true,
        minPieces: 8,
        defaultDiscountPercent: 35,
        requireMinPieces: true,
      },
      pinBadgedProductsToTop: true,
      outOfStockBehavior: 'badge-sold-out',
      topics: ['CONJUNTOS', 'MACACÕES', 'SHORTS', 'ROUPA MASCULINA TREINO'],
      products: [],
    },
  },

  // 4. Roupas Modinhas / Tendência (Minimal Trendy)
  {
    id: 'modinha',
    name: 'Roupas Modinhas & Tendências',
    categoryName: 'Moda Tendência & Looks Virais',
    tagline: 'Os looks mais desejados com apresentação clean e elegante',
    description: 'Estilo jovem e viral com layout organizado, minimalista e fotos em destaque.',
    thumbnail: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80',
    config: {
      storeName: 'GLOW UP CLOSET',
      slug: 'glowup-closet',
      bio: 'Os looks virais mais pedidos do TikTok e Reels com caimento impecável.',
      heroTagline: 'TENDÊNCIAS & NOVIDADES',
      heroTitle: 'Os looks perfeitos para você',
      heroHighlightWord: 'arrasar',
      heroSubtitle: 'Peças exclusivas, tendências internacionais e novidades que chegam toda semana.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1200&auto=format&fit=crop&q=80',
      instagram: '@glowup.closet',
      whatsapp: '5511955554444',
      locationText: 'São Paulo • Enviamos pro Brasil todo',
      templateId: 'modinha',
      theme: {
        primaryColor: '#BE185D',
        accentColor: '#DB2777',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#1F2937',
        mutedTextColor: '#6B7280',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'trendy-syne',
        typographyPresetId: 'trendy-syne',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: false,
      },
      progressiveDiscounts: [
        { minItems: 2, discountPercent: 10, label: '2 peças: 10% OFF' },
        { minItems: 3, discountPercent: 15, label: '3 peças: 15% OFF' },
      ],
      shipping: {
        pickupEnabled: false,
        pickupLabel: '',
        pickupAddress: '',
        motoboyEnabled: true,
        motoboyPrice: 12.0,
        motoboyEstimate: 'Entrega expressa capital',
        sedexEnabled: true,
        sedexPrice: 20.0,
        sedexEstimate: 'Correios todo o Brasil',
        freeShippingAbove: 199.0,
      },
      wholesaleConfig: {
        enabled: true,
        minPieces: 10,
        defaultDiscountPercent: 40,
        requireMinPieces: true,
      },
      pinBadgedProductsToTop: true,
      outOfStockBehavior: 'badge-sold-out',
      topics: ['CROPPEDS', 'CALÇAS', 'VESTIDOS', 'CONJUNTOS'],
      products: [],
    },
  },

  // 5. Streetwear & Urban Style (Minimal Raw)
  {
    id: 'streetwear',
    name: 'Streetwear & Urban Style',
    categoryName: 'Cultura Urbana & Skatewear',
    tagline: 'Cortes boxy, malha pesada e tipografia moderna minimalista',
    description: 'Estética clean industrial com preto fosco e tipografia de impacto.',
    thumbnail: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=600&auto=format&fit=crop&q=80',
    config: {
      storeName: 'RAW STREETWEAR',
      slug: 'raw-streetwear',
      bio: 'Estética urbana, cortes boxy e malhas pesadas de 260g a 450g.',
      heroTagline: 'CULTURA URBANA & HEAVYWEIGHT',
      heroTitle: 'O autêntico streetwear para você',
      heroHighlightWord: 'marcar presença',
      heroSubtitle: 'Drops limitados com peças numeradas e tecidos de altíssima gramatura.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=1200&auto=format&fit=crop&q=80',
      instagram: '@raw.streetbrand',
      whatsapp: '5511944443333',
      locationText: 'Centro, São Paulo • Envio Imediato',
      templateId: 'streetwear',
      theme: {
        primaryColor: '#18181B',
        accentColor: '#EA580C',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#09090B',
        mutedTextColor: '#71717A',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'street-space',
        typographyPresetId: 'street-space',
        layoutStyle: 'grid-2',
        badgeStyle: 'flat',
        enableGlassmorphism: false,
        heroCardBackground: '#18181B',
        heroCardTextColor: '#FFFFFF',
        heroCardBorderColor: '#27272A',
      },
      progressiveDiscounts: [
        { minItems: 2, discountPercent: 10, label: 'Combo Street: 2 peças = 10% OFF' },
      ],
      shipping: {
        pickupEnabled: true,
        pickupLabel: 'Galeria do Rock (Loja Física)',
        pickupAddress: 'Rua 24 de Maio, 62',
        motoboyEnabled: true,
        motoboyPrice: 16.0,
        motoboyEstimate: 'Entrega rápida hoje',
        sedexEnabled: true,
        sedexPrice: 25.0,
        sedexEstimate: 'Sedex com rastreio',
        freeShippingAbove: 299.0,
      },
      wholesaleConfig: {
        enabled: true,
        minPieces: 6,
        defaultDiscountPercent: 30,
        requireMinPieces: true,
      },
      pinBadgedProductsToTop: true,
      outOfStockBehavior: 'badge-sold-out',
      topics: ['MOLETONS', 'CAMISETAS', 'CALÇAS & BERMUDAS', 'ROUPA MASCULINA'],
      products: [],
    },
  },

  // 6. Moda Praia & Biquínis (Minimal Resort)
  {
    id: 'praia',
    name: 'Moda Praia & Biquínis',
    categoryName: 'Beachwear & Resort',
    tagline: 'Estética resort minimalista, modelagens delicadas e proteção solar',
    description: 'Design sofisticado de moda praia com paleta areia suave e peças que valorizam o corpo.',
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80',
    config: {
      storeName: 'MARESIA BEACHWEAR',
      slug: 'maresia-praia',
      bio: 'Biquínis e maiôs biodegradáveis com proteção UV50+ e toque acetinado.',
      heroTagline: 'BEACHWEAR & RESORT',
      heroTitle: 'A modelagem perfeita para o seu',
      heroHighlightWord: 'verão',
      heroSubtitle: 'Modelagens exclusivas que não marcam, tecidos com toque de seda e secagem rápida.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
      instagram: '@maresia.beachwear',
      whatsapp: '5511933332222',
      locationText: 'São Paulo & Litoral • Envio Brasil',
      templateId: 'praia',
      theme: {
        primaryColor: '#C27803',
        accentColor: '#0284C7',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#1E293B',
        mutedTextColor: '#64748B',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'praia-cinzel',
        typographyPresetId: 'praia-cinzel',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: false,
      },
      progressiveDiscounts: [
        { minItems: 2, discountPercent: 10, label: '2 peças ganham 10% OFF' },
      ],
      shipping: {
        pickupEnabled: false,
        pickupLabel: '',
        pickupAddress: '',
        motoboyEnabled: true,
        motoboyPrice: 15.0,
        motoboyEstimate: 'Chega hoje antes da sua viagem',
        sedexEnabled: true,
        sedexPrice: 26.0,
        sedexEstimate: 'Sedex prioritário Brasil',
        freeShippingAbove: 299.0,
      },
      wholesaleConfig: {
        enabled: true,
        minPieces: 6,
        defaultDiscountPercent: 35,
        requireMinPieces: true,
      },
      pinBadgedProductsToTop: true,
      outOfStockBehavior: 'badge-sold-out',
      topics: ['BIQUÍNIS', 'MAIÔS', 'SAÍDAS DE PRAIA', 'BERMUDAS MASCULINAS'],
      products: [],
    },
  },

  // 7. Cosméticos & Skincare (Clean Beauty)
  {
    id: 'skincare',
    name: 'Cosméticos & Skincare',
    categoryName: 'Dermocosméticos & Beleza Limpa',
    tagline: 'Fórmulas puras, dermatológicas e design minimalista botânico',
    description: 'Apresentação limpa, científica e serena para dermocosméticos e skincare.',
    thumbnail: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80',
    config: {
      storeName: 'BOTANIQUE SKINCARE',
      slug: 'botanique-skincare',
      bio: 'Skincare vegano de alta performance formulado por dermatologistas.',
      heroTagline: 'DERMOCOSMÉTICOS & ATIVOS NATURAIS',
      heroTitle: 'O cuidado certo para a sua pele',
      heroHighlightWord: 'radiar',
      heroSubtitle: 'Alta concentração de ativos, fórmulas cruelty-free e resultados comprovados em 14 dias.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=1200&auto=format&fit=crop&q=80',
      instagram: '@botanique.skincare',
      whatsapp: '5511922221111',
      locationText: 'São Paulo • Fórmulas Aprovadas Anvisa',
      templateId: 'skincare',
      theme: {
        primaryColor: '#166534',
        accentColor: '#15803D',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#14532D',
        mutedTextColor: '#4B5563',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'beauty-dmserif',
        typographyPresetId: 'beauty-dmserif',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: false,
      },
      progressiveDiscounts: [
        { minItems: 2, discountPercent: 10, label: 'Kit Rotina: 2 produtos com 10% OFF' },
      ],
      shipping: {
        pickupEnabled: true,
        pickupLabel: 'Retirada no Consultório (Vila Mariana)',
        pickupAddress: 'Rua Domingos de Morais, 1400',
        motoboyEnabled: true,
        motoboyPrice: 12.0,
        motoboyEstimate: 'Chega hoje',
        sedexEnabled: true,
        sedexPrice: 20.0,
        sedexEstimate: 'Correios todo o Brasil',
        freeShippingAbove: 220.0,
      },
      wholesaleConfig: {
        enabled: true,
        minPieces: 6,
        defaultDiscountPercent: 30,
        requireMinPieces: true,
      },
      pinBadgedProductsToTop: true,
      outOfStockBehavior: 'badge-sold-out',
      topics: ['SÉRUMS', 'CORPO', 'LIMPEZA FACIAL', 'HIDRATANTES'],
      products: [],
    },
  },

  // 8. Acessórios & Bolsas de Couro
  {
    id: 'acessorios',
    name: 'Acessórios & Bolsas de Couro',
    categoryName: 'Bolsas & Couro Legítimo',
    tagline: 'Couro legítimo, costura manual e sofisticação pura',
    description: 'Design elegante e clássico para marcas de bolsas e artigos em couro.',
    thumbnail: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop&q=80',
    config: {
      storeName: 'VERONA LEATHER & CO.',
      slug: 'verona-bolsas',
      bio: 'Bolsas estruturadas em couro legítimo selecionado com garantia vitalícia.',
      heroTagline: 'COURO LEGÍTIMO & DESIGN AUTORAL',
      heroTitle: 'O acabamento perfeito para você',
      heroHighlightWord: 'destacar',
      heroSubtitle: 'Ferragens banhadas, costuras reforçadas e modelagens clássicas que nunca saem de moda.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=1200&auto=format&fit=crop&q=80',
      instagram: '@verona.leather',
      whatsapp: '5511911110000',
      locationText: 'São Paulo • Garantia de 3 Anos',
      templateId: 'acessorios',
      theme: {
        primaryColor: '#78350F',
        accentColor: '#92400E',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#451A03',
        mutedTextColor: '#78350F',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'clean-outfit',
        typographyPresetId: 'clean-outfit',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: false,
      },
      progressiveDiscounts: [
        { minItems: 2, discountPercent: 10, label: 'Leve 2 peças com 10% OFF' },
      ],
      shipping: {
        pickupEnabled: true,
        pickupLabel: 'Ateliê Verona (Itaim Bibi)',
        pickupAddress: 'Rua Joaquim Floriano, 733',
        motoboyEnabled: true,
        motoboyPrice: 18.0,
        motoboyEstimate: 'Entrega expressa com embalagem de luxo',
        sedexEnabled: true,
        sedexPrice: 29.0,
        sedexEstimate: 'Correios todo o Brasil',
        freeShippingAbove: 499.0,
      },
      wholesaleConfig: {
        enabled: true,
        minPieces: 6,
        defaultDiscountPercent: 35,
        requireMinPieces: true,
      },
      pinBadgedProductsToTop: true,
      outOfStockBehavior: 'badge-sold-out',
      topics: ['BOLSAS', 'CINTOS', 'CARTEIRAS', 'ÓCULOS DE SOL'],
      products: [],
    },
  },

  // 9. Lingerie & Homewear (Sensual Minimal)
  {
    id: 'lingerie',
    name: 'Lingerie & Homewear Sensual',
    categoryName: 'Intimates & Sleepwear',
    tagline: 'Renda chantilly, seda pura e clima refinado intimista',
    description: 'Elegância e sensualidade com atmosfera minimalista e sofisticada.',
    thumbnail: 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&auto=format&fit=crop&q=80',
    config: {
      storeName: 'VELVET NOIR LINGERIE',
      slug: 'velvet-noir',
      bio: 'O poder da renda chantilly, seda e modelagens sem aro que abraçam suas curvas.',
      heroTagline: 'RENDAS FRANCESAS & SEDA PURA',
      heroTitle: 'A lingerie perfeita para você se',
      heroHighlightWord: 'apaixonar',
      heroSubtitle: 'Conforto sem aro, toque aveludado e caimento sob medida em todas as ocasiões.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=1200&auto=format&fit=crop&q=80',
      instagram: '@velvet.noirintimates',
      whatsapp: '5511900009999',
      locationText: 'Envio 100% discreto em embalagem perfumada',
      templateId: 'lingerie',
      theme: {
        primaryColor: '#881337',
        accentColor: '#9F1239',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#1C1917',
        mutedTextColor: '#78716C',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'sensual-prata',
        typographyPresetId: 'sensual-prata',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: false,
      },
      progressiveDiscounts: [
        { minItems: 2, discountPercent: 12, label: 'Leve 2 peças e ganhe 12% OFF' },
      ],
      shipping: {
        pickupEnabled: false,
        pickupLabel: '',
        pickupAddress: '',
        motoboyEnabled: true,
        motoboyPrice: 15.0,
        motoboyEstimate: 'Entrega super discreta em caixa lacrada',
        sedexEnabled: true,
        sedexPrice: 22.0,
        sedexEstimate: 'Correios todo o Brasil',
        freeShippingAbove: 279.0,
      },
      wholesaleConfig: {
        enabled: true,
        minPieces: 6,
        defaultDiscountPercent: 35,
        requireMinPieces: true,
      },
      pinBadgedProductsToTop: true,
      outOfStockBehavior: 'badge-sold-out',
      topics: ['BODIES', 'ROBES', 'CONJUNTOS', 'CALCINHAS'],
      products: [],
    },
  },

  // 10. Calçados & Sneakers (Hype Footwear Minimal)
  {
    id: 'sneakers',
    name: 'Calçados & Sneakers',
    categoryName: 'Calçados & Sneakers',
    tagline: 'Os pares mais cobiçados em couro legítimo e sola costurada',
    description: 'Estética clean minimalista com foco nas linhas dos calçados e sneakers.',
    thumbnail: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
    config: {
      storeName: 'STEP UP SHOES',
      slug: 'stepup-shoes',
      bio: 'Sneakers autênticos em couro legítimo selecionado e conforto anatômico.',
      heroTagline: 'CALÇADOS & SNEAKERS DE COURO',
      heroTitle: 'O calçado perfeito para o seu',
      heroHighlightWord: 'dia a dia',
      heroSubtitle: 'Palmilha anti-impacto em gel, costura 360 graus e troca grátis na primeira compra.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=1200&auto=format&fit=crop&q=80',
      instagram: '@stepup.footwear',
      whatsapp: '5511999990000',
      locationText: 'Franca, SP • Tradição Calçadista Nacional',
      templateId: 'sneakers',
      theme: {
        primaryColor: '#0F172A',
        accentColor: '#2563EB',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#0F172A',
        mutedTextColor: '#64748B',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'hype-epilogue',
        typographyPresetId: 'hype-epilogue',
        layoutStyle: 'grid-2',
        badgeStyle: 'flat',
        enableGlassmorphism: false,
        heroCardBackground: '#18181B',
        heroCardTextColor: '#FFFFFF',
        heroCardBorderColor: '#27272A',
      },
      progressiveDiscounts: [
        { minItems: 2, discountPercent: 15, label: 'Leve 2 pares com 15% OFF' },
      ],
      shipping: {
        pickupEnabled: false,
        pickupLabel: '',
        pickupAddress: '',
        motoboyEnabled: true,
        motoboyPrice: 18.0,
        motoboyEstimate: 'Mesmo dia na Grande SP',
        sedexEnabled: true,
        sedexPrice: 28.0,
        sedexEstimate: 'Correios todo o Brasil',
        freeShippingAbove: 349.0,
      },
      wholesaleConfig: {
        enabled: true,
        minPieces: 4,
        defaultDiscountPercent: 25,
        requireMinPieces: true,
      },
      pinBadgedProductsToTop: true,
      outOfStockBehavior: 'badge-sold-out',
      topics: ['SNEAKERS', 'PAPETES', 'CASUAIS URBANOS', 'MEIAS & CUIDADOS'],
      products: [],
    },
  },

  // 11. Smart Tech, Relógios & Celulares
  {
    id: 'smart-tech',
    name: 'Smart Tech, Relógios & Celulares',
    categoryName: 'Eletrônicos & Smartwatches',
    tagline: 'Smartwatches de alta performance, relógios de precisão, smartphones e fones sem fio',
    description: 'Estética tecnológica dark moderna inspirada na Apple e gadgets de ponta: cards com contraste refinado, tópicos especializados com ícones temáticos e alta conversão.',
    thumbnail: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&auto=format&fit=crop&q=80',
    config: {
      storeName: 'NEXUS SMART TECH',
      slug: 'nexus-tech',
      bio: 'Smartphones, Smartwatches, Fones de Ouvido, Relógios e Pulseiras com Garantia de 1 Ano.',
      heroTagline: 'TECNOLOGIA & CONECTIVIDADE',
      heroTitle: 'Os aparelhos e acessórios certos para o seu',
      heroHighlightWord: 'dia a dia',
      heroSubtitle: 'Produtos originais com garantia de 1 ano, pronta entrega e envio expresso para todo o Brasil.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1200&auto=format&fit=crop&q=80',
      instagram: '@nexus.smarttech',
      whatsapp: '5511999998888',
      locationText: 'São Paulo • Garantia Oficial 1 Ano',
      templateId: 'smart-tech',
      theme: {
        primaryColor: '#0284C7',
        accentColor: '#38BDF8',
        backgroundColor: '#0F172A',
        cardBackground: '#1E293B',
        textColor: '#F8FAFC',
        mutedTextColor: '#94A3B8',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'clean-outfit',
        typographyPresetId: 'clean-outfit',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: true,
        heroCardBackground: '#1E293B',
        heroCardTextColor: '#F8FAFC',
        heroCardBorderColor: 'rgba(255,255,255,0.12)',
      },
      progressiveDiscounts: [
        { minItems: 2, discountPercent: 10, label: 'Compre 2 itens e ganhe 10% OFF' },
        { minItems: 3, discountPercent: 15, label: 'Compre 3 itens e ganhe 15% OFF' },
      ],
      shipping: {
        pickupEnabled: true,
        pickupLabel: 'Retirada Expressa (Av. Paulista)',
        pickupAddress: 'Av. Paulista, 1800 - Bela Vista, SP',
        motoboyEnabled: true,
        motoboyPrice: 19.9,
        motoboyEstimate: 'Entrega hoje no mesmo dia',
        sedexEnabled: true,
        sedexPrice: 28.0,
        sedexEstimate: 'Correios todo o Brasil com seguro',
        freeShippingAbove: 499.0,
      },
      wholesaleConfig: {
        enabled: true,
        minPieces: 5,
        defaultDiscountPercent: 25,
        requireMinPieces: true,
      },
      pinBadgedProductsToTop: true,
      outOfStockBehavior: 'badge-sold-out',
      topics: [
        'RELÓGIOS',
        'PULSEIRAS',
        'SMARTWATCHES',
        'TELEFONES',
        'FONES DE OUVIDO',
      ],
      products: [],
    },
  },

  // 12. Começar do Zero (Em Branco)
  {
    id: 'custom',
    name: 'Começar do Zero (Em Branco)',
    categoryName: 'Totalmente Personalizável',
    tagline: 'Crie seu catálogo do seu jeito com layout e cores livres',
    description: 'Tela limpa para você cadastrar seus produtos e montar a identidade visual exata do seu negócio.',
    thumbnail: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
    config: {
      storeName: 'MINHA BOUTIQUE',
      slug: 'minha-loja',
      bio: 'Catálogo online de peças selecionadas.',
      heroTagline: 'COLEÇÃO EXCLUSIVA',
      heroTitle: 'As peças certas para você',
      heroHighlightWord: 'encantar',
      heroSubtitle: 'Escolha suas peças favoritas e finalize seu pedido diretamente pelo WhatsApp.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&auto=format&fit=crop&q=80',
      instagram: '@minhaloja',
      whatsapp: '5511999999999',
      locationText: 'Brasil • Atendimento Online',
      templateId: 'custom',
      theme: {
        primaryColor: '#B8860B',
        accentColor: '#D4AF37',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#1C1917',
        mutedTextColor: '#78716C',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'clean-outfit',
        typographyPresetId: 'clean-outfit',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: false,
      },
      progressiveDiscounts: [
        { minItems: 2, discountPercent: 10, label: 'Compre 2 ganhe 10% OFF' },
      ],
      shipping: {
        pickupEnabled: true,
        pickupLabel: 'Retirada na Loja',
        pickupAddress: 'Endereço da sua loja',
        motoboyEnabled: true,
        motoboyPrice: 15.0,
        motoboyEstimate: 'Entrega motoboy',
        sedexEnabled: true,
        sedexPrice: 25.0,
        sedexEstimate: 'Envio Correios',
        freeShippingAbove: 299.0,
      },
      wholesaleConfig: {
        enabled: false,
        minPieces: 6,
        defaultDiscountPercent: 30,
        requireMinPieces: true,
      },
      pinBadgedProductsToTop: true,
      outOfStockBehavior: 'badge-sold-out',
      topics: ['Novidades', 'Destaques', 'Mais Vendidos'],
      products: [],
    },
  },

  // 13. Alimentos & Gastronomia Artesanal (Doceria, Bolos & Confeitaria)
  {
    id: 'gastronomia',
    name: 'Doceria, Bolos & Gastronomia Artesanal',
    categoryName: 'Alimentos & Confeitaria Artesanal',
    tagline: 'Bolos decorados, doces finos, brigadeiros gourmet e encomendas para festas',
    description: 'Apresentação apetitosa e sofisticada com fotos em alta definição, tópicos organizados por tipo de doce e pedido direto no WhatsApp.',
    thumbnail: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80',
    segment: 'products',
    config: {
      storeName: 'ATELIÊ DO DOCE & CONFEITARIA',
      slug: 'atelie-gastronomia',
      bio: 'Bolos festivos sob encomenda, doces finos para casamentos e brigadeiros gourmet artesanais.',
      heroTagline: 'CONFEITARIA ARTESANAL & FESTAS',
      heroTitle: 'Os sabores mais especiais para você',
      heroHighlightWord: 'celebrar',
      heroSubtitle: 'Ingredientes nobres, chocolate belga 100% puro e encomendas com entrega pontual na sua festa.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1517433670267-08bbd4be890f?w=1200&auto=format&fit=crop&q=80',
      instagram: '@ateliedodoce.artesanal',
      whatsapp: '5511977778888',
      locationText: 'São Paulo • Encomendas com 24h a 48h de antecedência',
      templateId: 'gastronomia',
      businessType: 'products',
      actionButtonLabel: 'Adicionar ao Pedido',
      theme: {
        primaryColor: '#D97706',
        accentColor: '#B45309',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#451A03',
        mutedTextColor: '#78350F',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'semijoias-cormorant',
        typographyPresetId: 'semijoias-cormorant',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: false,
      },
      progressiveDiscounts: [
        { minItems: 2, discountPercent: 10, label: 'Leve 2 combos e ganhe 10% OFF' },
      ],
      shipping: {
        pickupEnabled: true,
        pickupLabel: 'Retirada no Ateliê (Moema/SP)',
        pickupAddress: 'Alameda dos Anapurus, 1250',
        motoboyEnabled: true,
        motoboyPrice: 15.0,
        motoboyEstimate: 'Entrega refrigerada no dia',
        sedexEnabled: false,
        sedexPrice: 0,
        sedexEstimate: '',
        freeShippingAbove: 250.0,
      },
      wholesaleConfig: {
        enabled: true,
        minPieces: 50,
        defaultDiscountPercent: 20,
        requireMinPieces: true,
      },
      pinBadgedProductsToTop: true,
      outOfStockBehavior: 'badge-sold-out',
      topics: ['BOLOS DECORADOS', 'DOCES FINOS & BRIGADEIROS', 'TORTAS & SOBREMESAS', 'SALGADOS ARTESANAIS', 'COMBOS PARA FESTA'],
      topicIcons: {
        'BOLOS DECORADOS': 'cake',
        'DOCES FINOS & BRIGADEIROS': 'cake',
        'TORTAS & SOBREMESAS': 'cake',
        'SALGADOS ARTESANAIS': 'utensils',
        'COMBOS PARA FESTA': 'sparkles',
      },
      products: [],
    },
  },

  // 14. Serviços: Estética Automotiva & Lava-Rápido Premium
  {
    id: 'estetica-automotiva',
    name: 'Estética Automotiva & Lava-Rápido Premium',
    categoryName: 'Serviços Automotivos & Detailing',
    tagline: 'Lavagem detalhada com vapor, higienização interna profunda, polimento e vitrificação',
    description: 'Apresentação robusta para estúdios automotivos: grade de horários, tempo estimado por serviço e agendamento rápido com confirmação via WhatsApp.',
    thumbnail: 'https://images.unsplash.com/photo-1601362840469-51e4d8d58785?w=600&auto=format&fit=crop&q=80',
    segment: 'services',
    config: {
      storeName: 'AUTO GLOSS DETAIL & SPA',
      slug: 'auto-gloss',
      bio: 'Estética automotiva especializada em lavagem técnica, vitrificação de pintura e higienização interna profunda.',
      heroTagline: 'ESTÉTICA AUTOMOTIVA & DETAILING',
      heroTitle: 'O cuidado premium que o seu carro',
      heroHighlightWord: 'merece',
      heroSubtitle: 'Produtos biodegradáveis alemães, estúdio 100% climatizado com iluminação técnica e garantia em vitrificações.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1601362840469-51e4d8d58785?w=1200&auto=format&fit=crop&q=80',
      instagram: '@autogloss.detail',
      whatsapp: '5511999991234',
      locationText: 'São Paulo • Sala VIP com Wi-Fi e Café',
      templateId: 'estetica-automotiva',
      businessType: 'services',
      actionButtonLabel: 'Agendar Horário',
      schedulingConfig: {
        enabled: true,
        allowDirectBooking: true,
        slotDurationMinutes: 60,
        businessHours: 'Segunda a Sábado: 08:00 às 18:30',
        workingDays: ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
        timeSlots: ['08:00', '09:30', '11:00', '13:30', '15:00', '16:30'],
        serviceNotice: 'Carros com barro excessivo ou interior com manchas graves passam por avaliação prévia na recepção.',
      },
      theme: {
        primaryColor: '#0284C7',
        accentColor: '#38BDF8',
        backgroundColor: '#0B0F19',
        cardBackground: '#111827',
        textColor: '#F9FAFB',
        mutedTextColor: '#9CA3AF',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'clean-outfit',
        typographyPresetId: 'clean-outfit',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: true,
        heroCardBackground: '#111827',
        heroCardTextColor: '#F9FAFB',
        heroCardBorderColor: 'rgba(255,255,255,0.1)',
      },
      progressiveDiscounts: [],
      shipping: {
        pickupEnabled: false,
        pickupLabel: '',
        pickupAddress: '',
        motoboyEnabled: false,
        motoboyPrice: 0,
        motoboyEstimate: '',
        sedexEnabled: false,
        sedexPrice: 0,
        sedexEstimate: '',
      },
      topics: ['LAVAGEM DETALHADA', 'HIGIENIZAÇÃO INTERNA', 'POLIMENTO & CRISTALIZAÇÃO', 'VITRIFICAÇÃO & PROTEÇÃO', 'SERVIÇOS RÁPIDOS'],
      topicIcons: {
        'LAVAGEM DETALHADA': 'car',
        'HIGIENIZAÇÃO INTERNA': 'armchair',
        'POLIMENTO & CRISTALIZAÇÃO': 'sparkles',
        'VITRIFICAÇÃO & PROTEÇÃO': 'shield-check',
        'SERVIÇOS RÁPIDOS': 'clock',
      },
      products: [],
    },
  },

  // 15. Serviços: Nail Designer & Esmalteria
  {
    id: 'nail-designer',
    name: 'Nail Designer & Esmalteria',
    categoryName: 'Unhas, Alongamentos & Spa',
    tagline: 'Alongamento em gel, fibra de vidro, blindagem diamante e nail art exclusiva',
    description: 'Estética delicada em tons rose gold para manicures e nail designers: exibe tempo de aplicação de cada procedimento e horários vagos.',
    thumbnail: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=600&auto=format&fit=crop&q=80',
    segment: 'services',
    config: {
      storeName: 'L’ATELIER NAILS & SPA',
      slug: 'latelier-nails',
      bio: 'Especialista em fibra de vidro, banho em gel e esmaltação em gel com durabilidade de até 25 dias.',
      heroTagline: 'NAIL DESIGNER & ESMALTERIA DE LUXO',
      heroTitle: 'O design perfeito para as suas unhas',
      heroHighlightWord: 'brilharem',
      heroSubtitle: 'Materiais 100% esterilizados em autoclave, produtos importados e atendimento individualizado com hora marcada.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=1200&auto=format&fit=crop&q=80',
      instagram: '@latelier.nails',
      whatsapp: '5511988882222',
      locationText: 'São Paulo • Atendimento com Hora Marcada',
      templateId: 'nail-designer',
      businessType: 'services',
      actionButtonLabel: 'Agendar Horário',
      schedulingConfig: {
        enabled: true,
        allowDirectBooking: true,
        slotDurationMinutes: 90,
        businessHours: 'Terça a Sábado: 09:00 às 19:00',
        workingDays: ['Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
        timeSlots: ['09:00', '10:30', '13:00', '14:30', '16:00', '17:30'],
        serviceNotice: 'Tolerância de 10 minutos de atraso para não comprometer as clientes seguintes.',
      },
      theme: {
        primaryColor: '#BE185D',
        accentColor: '#F472B6',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#831843',
        mutedTextColor: '#9D174D',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'semijoias-cormorant',
        typographyPresetId: 'semijoias-cormorant',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: false,
      },
      progressiveDiscounts: [],
      shipping: {
        pickupEnabled: false,
        pickupLabel: '',
        pickupAddress: '',
        motoboyEnabled: false,
        motoboyPrice: 0,
        motoboyEstimate: '',
        sedexEnabled: false,
        sedexPrice: 0,
        sedexEstimate: '',
      },
      topics: ['ALONGAMENTO EM GEL', 'FIBRA DE VIDRO', 'BLINDAGEM & ESMALTAÇÃO', 'MANICURE & SPA DOS PÉS', 'NAIL ART EXCLUSIVA'],
      topicIcons: {
        'ALONGAMENTO EM GEL': 'sparkles',
        'FIBRA DE VIDRO': 'gem',
        'BLINDAGEM & ESMALTAÇÃO': 'palette',
        'MANICURE & SPA DOS PÉS': 'heart',
        'NAIL ART EXCLUSIVA': 'crown',
      },
      products: [],
    },
  },

  // 16. Serviços: Salão de Cabelo & Hair Studio
  {
    id: 'salao-cabelo',
    name: 'Salão de Cabelo & Hair Studio',
    categoryName: 'Cabelos, Mechas & Visagismo',
    tagline: 'Cortes com visagismo, mechas loiras e morena iluminada, cronograma e botox capilar',
    description: 'Visual sofisticado para hair stylists e salões de beleza: exibe tempo médio de cadeira por serviço, procedimentos com consulta prévia e agendamento online.',
    thumbnail: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=600&auto=format&fit=crop&q=80',
    segment: 'services',
    config: {
      storeName: 'MAISON HAIR STUDIO',
      slug: 'maison-hair',
      bio: 'Mechas personalizadas, cortes modernos com visagismo e tratamentos capilares de alta tecnologia.',
      heroTagline: 'HAIR STYLING & COLORIMETRIA',
      heroTitle: 'A transformação perfeita para o seu',
      heroHighlightWord: 'cabelo',
      heroSubtitle: 'Diagnóstico capilar gratuito antes de qualquer procedimento de descoloração. Agende seu horário com os nossos hair stylists.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&auto=format&fit=crop&q=80',
      instagram: '@maison.hairstudio',
      whatsapp: '5511988883333',
      locationText: 'Jardins, São Paulo • Valet e Bar no local',
      templateId: 'salao-cabelo',
      businessType: 'services',
      actionButtonLabel: 'Agendar Horário',
      schedulingConfig: {
        enabled: true,
        allowDirectBooking: true,
        slotDurationMinutes: 60,
        businessHours: 'Terça a Sábado: 09:00 às 20:00',
        workingDays: ['Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
        timeSlots: ['09:00', '10:30', '13:00', '14:30', '16:00', '17:30', '19:00'],
        serviceNotice: 'Para mechas ou transformações completas, recomenda-se realizar teste de mecha prévio.',
      },
      theme: {
        primaryColor: '#1C1917',
        accentColor: '#D97706',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#1C1917',
        mutedTextColor: '#78716C',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'boutique-playfair',
        typographyPresetId: 'boutique-playfair',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: false,
      },
      progressiveDiscounts: [],
      shipping: {
        pickupEnabled: false,
        pickupLabel: '',
        pickupAddress: '',
        motoboyEnabled: false,
        motoboyPrice: 0,
        motoboyEstimate: '',
        sedexEnabled: false,
        sedexPrice: 0,
        sedexEstimate: '',
      },
      topics: ['CORTES & VISAGISMO', 'MECHAS & ILUMINADOS', 'TRATAMENTOS & CRONOGRAMA', 'ESCOVAS & PENTEADOS', 'ALISAMENTOS & BOTOX'],
      topicIcons: {
        'CORTES & VISAGISMO': 'scissors',
        'MECHAS & ILUMINADOS': 'sparkles',
        'TRATAMENTOS & CRONOGRAMA': 'heart',
        'ESCOVAS & PENTEADOS': 'crown',
        'ALISAMENTOS & BOTOX': 'flame',
      },
      products: [],
    },
  },

  // 17. Serviços: Barbearia & Grooming Masculino
  {
    id: 'barbearia',
    name: 'Barbearia & Grooming Masculino',
    categoryName: 'Barbearia & Cuidados Masculinos',
    tagline: 'Cortes degradê impecáveis, barba na toalha quente e tratamentos masculinos',
    description: 'Estética vintage moderna com tons escuros e couro para barbearias: agendamento com grade rápida de 30 a 45 minutos e confirmação automática.',
    thumbnail: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=600&auto=format&fit=crop&q=80',
    segment: 'services',
    config: {
      storeName: 'DON CORLEONE BARBERSHOP',
      slug: 'don-corleone',
      bio: 'A autêntica experiência de barbearia clássica: toalha quente, navalha afiada e cerveja artesanal.',
      heroTagline: 'TRADIÇÃO, ESTILO & GROOMING',
      heroTitle: 'O corte e a barba perfeitos para a sua',
      heroHighlightWord: 'presença',
      heroSubtitle: 'Ambiente aconchegante, barbeiros experientes e atendimento com pontualidade britânica. Escolha seu serviço e garanta sua cadeira.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=1200&auto=format&fit=crop&q=80',
      instagram: '@doncorleone.barber',
      whatsapp: '5511977774444',
      locationText: 'São Paulo • Cerveja cortesia e Sinuca',
      templateId: 'barbearia',
      businessType: 'services',
      actionButtonLabel: 'Agendar Horário',
      schedulingConfig: {
        enabled: true,
        allowDirectBooking: true,
        slotDurationMinutes: 45,
        businessHours: 'Segunda a Sábado: 09:00 às 21:00',
        workingDays: ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
        timeSlots: ['09:00', '09:45', '10:30', '11:15', '13:00', '14:00', '15:00', '16:00', '17:00', '18:00', '19:00', '20:00'],
        serviceNotice: 'Cerveja artesanal ou café expresso cortesia durante o atendimento.',
      },
      theme: {
        primaryColor: '#78350F',
        accentColor: '#D97706',
        backgroundColor: '#0F172A',
        cardBackground: '#1E293B',
        textColor: '#F8FAFC',
        mutedTextColor: '#94A3B8',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'clean-outfit',
        typographyPresetId: 'clean-outfit',
        layoutStyle: 'grid-2',
        badgeStyle: 'flat',
        enableGlassmorphism: false,
        heroCardBackground: '#1E293B',
        heroCardTextColor: '#F8FAFC',
        heroCardBorderColor: 'rgba(255,255,255,0.1)',
      },
      progressiveDiscounts: [],
      shipping: {
        pickupEnabled: false,
        pickupLabel: '',
        pickupAddress: '',
        motoboyEnabled: false,
        motoboyPrice: 0,
        motoboyEstimate: '',
        sedexEnabled: false,
        sedexPrice: 0,
        sedexEstimate: '',
      },
      topics: ['CORTES DE CABELO', 'BARBA COM TOALHA QUENTE', 'COMBOS CABELO + BARBA', 'QUÍMICA & PIGMENTAÇÃO', 'TRATAMENTO VIP'],
      topicIcons: {
        'CORTES DE CABELO': 'scissors',
        'BARBA COM TOALHA QUENTE': 'scissors',
        'COMBOS CABELO + BARBA': 'crown',
        'QUÍMICA & PIGMENTAÇÃO': 'sparkles',
        'TRATAMENTO VIP': 'crown',
      },
      products: [],
    },
  },

  // 18. Serviços: Higienização & Lavagem de Estofados
  {
    id: 'lavagem-estofados',
    name: 'Higienização & Lavagem de Estofados',
    categoryName: 'Higienização & Limpeza Profissional',
    tagline: 'Higienização profunda a seco de sofás, colchões, poltronas e impermeabilização',
    description: 'Ideal para empresas de limpeza e higienização residencial/empresarial: orçamento rápido, atendimento em domicílio e escolha de período.',
    thumbnail: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop&q=80',
    segment: 'services',
    config: {
      storeName: 'CLEAN SOFÁ HIGIENIZAÇÃO',
      slug: 'clean-sofa',
      bio: 'Eliminação de até 99,9% de ácaros, fungos e bactérias com secagem rápida e produtos certificados pela ANVISA.',
      heroTagline: 'HIGIENIZAÇÃO & IMPERMEABILIZAÇÃO',
      heroTitle: 'A renovação e o frescor que o seu estofado',
      heroHighlightWord: 'precisa',
      heroSubtitle: 'Atendimento 100% em domicílio com maquinário extrator industrial italiano. Peça seu orçamento pelo WhatsApp ou escolha a data ideal.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&auto=format&fit=crop&q=80',
      instagram: '@cleansofa.higienizacao',
      whatsapp: '5511966663333',
      locationText: 'Grande São Paulo • Atendimento em Domicílio',
      templateId: 'lavagem-estofados',
      businessType: 'services',
      actionButtonLabel: 'Solicitar Orçamento / Agendamento',
      schedulingConfig: {
        enabled: true,
        allowDirectBooking: true,
        slotDurationMinutes: 120,
        businessHours: 'Segunda a Sábado: 08:00 às 18:00',
        workingDays: ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
        timeSlots: ['08:30 (Manhã)', '11:00 (Almoço)', '14:00 (Tarde)', '16:30 (Final de tarde)'],
        serviceNotice: 'Atendimento no conforto da sua residência. Necessário ponto de energia e água disponíveis no local.',
      },
      theme: {
        primaryColor: '#0D9488',
        accentColor: '#14B8A6',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#134E4A',
        mutedTextColor: '#0F766E',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'clean-outfit',
        typographyPresetId: 'clean-outfit',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: false,
      },
      progressiveDiscounts: [],
      shipping: {
        pickupEnabled: false,
        pickupLabel: '',
        pickupAddress: '',
        motoboyEnabled: false,
        motoboyPrice: 0,
        motoboyEstimate: '',
        sedexEnabled: false,
        sedexPrice: 0,
        sedexEstimate: '',
      },
      topics: ['SOFÁS & RETRÁTEIS', 'COLCHÕES & BOX', 'POLTRONAS & CADEIRAS', 'TAPETES & CARPETES', 'IMPERMEABILIZAÇÃO'],
      topicIcons: {
        'SOFÁS & RETRÁTEIS': 'armchair',
        'COLCHÕES & BOX': 'armchair',
        'POLTRONAS & CADEIRAS': 'armchair',
        'TAPETES & CARPETES': 'layers',
        'IMPERMEABILIZAÇÃO': 'shield-check',
      },
      products: [],
    },
  },

  // 19. Serviços: Studio de Maquiagem & Noivas
  {
    id: 'maquiagem',
    name: 'Studio de Maquiagem & Noivas',
    categoryName: 'Maquiagem Profissional & Noivas',
    tagline: 'Maquiagem social, produção de noivas, debutantes, formandas e pré-wedding',
    description: 'Estética glamourosa com acabamento iluminado para makeup artists: cronograma de produções para eventos com seleção de data do evento e horário de pronto.',
    thumbnail: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&auto=format&fit=crop&q=80',
    segment: 'services',
    config: {
      storeName: 'GLAM STUDIO MAKEUP',
      slug: 'glam-makeup',
      bio: 'Maquiagem à prova d’água de altíssima durabilidade com marcas importadas renomadas (Dior, MAC, Charlotte Tilbury).',
      heroTagline: 'MAKEUP ARTISTRY & NOIVAS',
      heroTitle: 'A maquiagem perfeita para você se',
      heroHighlightWord: 'destacar',
      heroSubtitle: 'Pele blindada, durabilidade de 24h e técnicas personalizadas para realçar sua beleza natural. Agende a sua data especial.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=1200&auto=format&fit=crop&q=80',
      instagram: '@glamstudio.makeup',
      whatsapp: '5511955552222',
      locationText: 'São Paulo • Atendimento em Studio e no Local do Evento',
      templateId: 'maquiagem',
      businessType: 'services',
      actionButtonLabel: 'Agendar Horário',
      schedulingConfig: {
        enabled: true,
        allowDirectBooking: true,
        slotDurationMinutes: 75,
        businessHours: 'Quarta a Domingo: 08:00 às 20:00',
        workingDays: ['Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
        timeSlots: ['08:00', '09:30', '11:00', '13:00', '14:30', '16:00', '17:30', '19:00'],
        serviceNotice: 'Vir com o rosto limpo e hidratado. Cílios postiços e preparação de pele inclusos em todas as produções.',
      },
      theme: {
        primaryColor: '#9333EA',
        accentColor: '#C084FC',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#581C87',
        mutedTextColor: '#7E22CE',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'semijoias-cormorant',
        typographyPresetId: 'semijoias-cormorant',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: false,
      },
      progressiveDiscounts: [],
      shipping: {
        pickupEnabled: false,
        pickupLabel: '',
        pickupAddress: '',
        motoboyEnabled: false,
        motoboyPrice: 0,
        motoboyEstimate: '',
        sedexEnabled: false,
        sedexPrice: 0,
        sedexEstimate: '',
      },
      topics: ['MAKE SOCIAL & FESTAS', 'PRODUÇÃO NOIVAS & PRÉ-WEDDING', 'MADRINHAS & FORMANDAS', 'MAKE EXPRESS & GLAM', 'DESIGN DE SOBRANCELHAS'],
      topicIcons: {
        'MAKE SOCIAL & FESTAS': 'sparkles',
        'PRODUÇÃO NOIVAS & PRÉ-WEDDING': 'crown',
        'MADRINHAS & FORMANDAS': 'sparkles',
        'MAKE EXPRESS & GLAM': 'flame',
        'DESIGN DE SOBRANCELHAS': 'scissors',
      },
      products: [],
    },
  },

  // 20. Serviços: Aluguel de Trajes Finos & Vestidos
  {
    id: 'aluguel-roupas',
    name: 'Aluguel de Trajes Finos & Vestidos',
    categoryName: 'Aluguel de Trajes & Vestidos de Festa',
    tagline: 'Vestidos de gala, madrinhas, ternos sob medida e trajes de debutantes com ajustes inclusos',
    description: 'Voltado para locação e aluguel de roupas de festa: agendamento de prova presencial com estilista, reserva de data do evento e retirada inclusa.',
    thumbnail: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&auto=format&fit=crop&q=80',
    segment: 'services',
    config: {
      storeName: 'IMPERIAL TRAJES & ALUGUEL',
      slug: 'imperial-trajes',
      bio: 'Aluguel de vestidos de festa assinados por estilistas, smokings e ternos finos com ajustes sob medida inclusos.',
      heroTagline: 'ALUGUEL DE TRAJES & ALTA COSTURA',
      heroTitle: 'O traje perfeito para a sua grande',
      heroHighlightWord: 'noite',
      heroSubtitle: 'Mais de 500 modelos exclusivos em pedraria e alfaiataria. Agende uma prova com nossa consultora de estilo e garanta seu look.',
      headerStyle: 'minimal-centered',
      avatarUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=300&auto=format&fit=crop&q=80',
      bannerUrl: 'https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=1200&auto=format&fit=crop&q=80',
      instagram: '@imperial.trajesfinos',
      whatsapp: '5511944441111',
      locationText: 'São Paulo • Provas com Estilista Exclusivo',
      templateId: 'aluguel-roupas',
      businessType: 'services',
      actionButtonLabel: 'Agendar Prova / Reserva',
      schedulingConfig: {
        enabled: true,
        allowDirectBooking: true,
        slotDurationMinutes: 60,
        businessHours: 'Segunda a Sábado: 09:30 às 19:00',
        workingDays: ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
        timeSlots: ['09:30', '11:00', '13:30', '15:00', '16:30', '18:00'],
        serviceNotice: 'Atendimento exclusivo com consultora de imagem. Ajustes de bainha e passadoria profissional inclusos no valor do aluguel.',
      },
      theme: {
        primaryColor: '#831843',
        accentColor: '#BE185D',
        backgroundColor: '#FFFFFF',
        cardBackground: '#FFFFFF',
        textColor: '#1C1917',
        mutedTextColor: '#78716C',
        buttonTextColor: '#FFFFFF',
        fontFamily: 'boutique-playfair',
        typographyPresetId: 'boutique-playfair',
        layoutStyle: 'grid-2',
        badgeStyle: 'pill',
        enableGlassmorphism: false,
      },
      progressiveDiscounts: [],
      shipping: {
        pickupEnabled: false,
        pickupLabel: '',
        pickupAddress: '',
        motoboyEnabled: false,
        motoboyPrice: 0,
        motoboyEstimate: '',
        sedexEnabled: false,
        sedexPrice: 0,
        sedexEstimate: '',
      },
      topics: ['VESTIDOS DE FESTA & GALA', 'VESTIDOS DE MADRINHA', 'TERNOS & SMOKING', 'DEBUTANTES', 'ACESSÓRIOS & CLUTCHES'],
      topicIcons: {
        'VESTIDOS DE FESTA & GALA': 'dress',
        'VESTIDOS DE MADRINHA': 'dress',
        'TERNOS & SMOKING': 'shirt',
        'DEBUTANTES': 'crown',
        'ACESSÓRIOS & CLUTCHES': 'shopping-bag',
      },
      products: [],
    },
  },
];

// Garante que todo template tenha segment, topics e topicIcons inicializados com base nas categorias
TEMPLATES.forEach((tmpl) => {
  if (!tmpl.segment) {
    tmpl.segment = tmpl.config.businessType === 'services' ? 'services' : 'products';
  }
  if (!tmpl.config.businessType) {
    tmpl.config.businessType = tmpl.segment === 'services' ? 'services' : 'products';
  }
  if (!tmpl.config.actionButtonLabel) {
    tmpl.config.actionButtonLabel = tmpl.segment === 'services' ? 'Agendar Horário' : 'Adicionar ao Pedido';
  }
  if (!tmpl.config.topics || tmpl.config.topics.length === 0) {
    tmpl.config.topics = ['Novidades', 'Destaques', 'Mais Vendidos'];
  }
  if (!tmpl.config.topicIcons) {
    tmpl.config.topicIcons = {};
  }
  tmpl.config.topics.forEach((t) => {
    if (!tmpl.config.topicIcons![t]) {
      tmpl.config.topicIcons![t] = suggestIconForTopic(t);
    }
  });
});

export function getTemplateById(idOrSlug: string): CatalogTemplate | undefined {
  return TEMPLATES.find(
    (t) => t.id === idOrSlug || t.config.slug === idOrSlug
  );
}

export function getDefaultCatalog(): CatalogConfig {
  const defaultCat: CatalogConfig = {
    storeName: 'Minha Loja',
    slug: 'minha-loja',
    bio: 'Catálogo oficial da loja. Escolha seus produtos e finalize pelo WhatsApp ou Direct.',
    heroTagline: 'CATÁLOGO OFICIAL',
    heroTitle: 'Encontre as melhores peças para você',
    heroHighlightWord: 'você',
    heroSubtitle: 'Escolha suas peças exclusivas com garantia de qualidade e envio rápido.',
    headerStyle: 'minimal-centered',
    avatarUrl: '/images/vitryne-logo-cropped.png',
    bannerUrl: '',
    instagram: '',
    whatsapp: '',
    locationText: '',
    templateId: 'default',
    theme: {
      primaryColor: '#0F172A',
      accentColor: '#3B82F6',
      backgroundColor: '#FFFFFF',
      cardBackground: '#FFFFFF',
      textColor: '#0F172A',
      mutedTextColor: '#64748B',
      buttonTextColor: '#FFFFFF',
      fontFamily: 'inter',
      typographyPresetId: 'inter',
      layoutStyle: 'grid-2',
      badgeStyle: 'pill',
      enableGlassmorphism: false,
    },
    progressiveDiscounts: [],
    shipping: {
      pickupEnabled: false,
      pickupLabel: 'Retirada no Local',
      pickupAddress: 'Endereço da Loja',
      motoboyEnabled: true,
      motoboyPrice: 15.0,
      motoboyEstimate: 'Entrega rápida no mesmo dia',
      sedexEnabled: true,
      sedexPrice: 25.0,
      sedexEstimate: 'Envio nacional',
      freeShippingAbove: 299.0,
    },
    wholesaleConfig: {
      enabled: false,
      minPieces: 6,
    },
    topics: ['NOVIDADES', 'DESTAQUES'],
    topicIcons: {
      NOVIDADES: 'sparkles',
      DESTAQUES: 'star',
    },
    products: [],
    businessType: 'products',
    actionButtonLabel: 'Comprar Agora',
    paymentConfig: {
      pixEnabled: true,
      pixKeyType: 'phone',
      pixKey: '',
      pixBeneficiaryName: '',
      pixBeneficiaryCity: 'São Paulo',
      allowWhatsAppDirectCheckout: true,
      showPixScreenWithProof: true,
    },
  };
  return defaultCat;
}
